DEFAULT_LANGUAGE = "tr"

STRINGS = {
    "tr": {
        "title": "Akıllı Sistem Monitörü",
        "health": "PC Sağlığı",
        "cpu": "CPU",
        "gpu": "GPU",
        "ram": "RAM",
        "ssd": "SSD",
        "disk": "Disk",
        "status": "Durum",
        "normal": "Normal",
        "high": "Yüksek",
        "critical": "Kritik",
        "warning": "Uyarı",
        "alerts": "Uyarılar",
        "no_alerts": "Aktif uyarı yok",
        "taskbar_mode": "Taskbar modu",
        "english": "EN",
        "turkish": "TR",
        "system_overview": "Sistem Özeti",
        "health_score": "Sağlık Skoru",
        "usage": "Kullanım",
        "temp": "Sıcaklık",
        "power": "Güç",
        "clock": "Saat",
        "fan": "Fan",
        "vram": "VRAM",
        "read_write": "Okuma / Yazma",
        "disk_health": "Disk Sağlığı",
        "storage": "Depolama",
        "history": "Geçmiş",
        "history_1m": "1 dk",
        "history_10m": "10 dk",
        "history_1h": "1 saat",
        "history_24h": "24 saat",
        "history_7d": "7 gün",
        "temperature": "Sıcaklık",
        "performance": "Performans",
        "last_updated": "Son güncelleme",
        "loading": "Yükleniyor...",
        "health_label": "Mükemmel",
        "cpu_label": "İyi",
        "gpu_label": "Dikkat",
        "ssd_label": "Mükemmel",
        "cooling_label": "Dengeli",
        "storage_label": "İyi",
        "unit_c": "°C",
        "unit_mb": "MB/s",
        "unit_gb": "GB",
        "unit_percent": "%",
    },
    "en": {
        "title": "Smart System Monitor",
        "health": "PC Health",
        "cpu": "CPU",
        "gpu": "GPU",
        "ram": "RAM",
        "ssd": "SSD",
        "disk": "Disk",
        "status": "Status",
        "normal": "Normal",
        "high": "High",
        "critical": "Critical",
        "warning": "Warning",
        "alerts": "Alerts",
        "no_alerts": "No active alerts",
        "taskbar_mode": "Taskbar mode",
        "english": "EN",
        "turkish": "TR",
        "system_overview": "System Overview",
        "health_score": "Health Score",
        "usage": "Usage",
        "temp": "Temperature",
        "power": "Power",
        "clock": "Clock",
        "fan": "Fan",
        "vram": "VRAM",
        "read_write": "Read / Write",
        "disk_health": "Disk Health",
        "storage": "Storage",
        "history": "History",
        "history_1m": "1 min",
        "history_10m": "10 min",
        "history_1h": "1 hour",
        "history_24h": "24 hours",
        "history_7d": "7 days",
        "temperature": "Temperature",
        "performance": "Performance",
        "last_updated": "Last updated",
        "loading": "Loading...",
        "health_label": "Excellent",
        "cpu_label": "Good",
        "gpu_label": "Watch",
        "ssd_label": "Excellent",
        "cooling_label": "Balanced",
        "storage_label": "Good",
        "unit_c": "°C",
        "unit_mb": "MB/s",
        "unit_gb": "GB",
        "unit_percent": "%",
    },
}
